GET http://localhost:3001/api/persons

###

GET http://localhost:3001/api/persons/624df43d83b61c8f60e980de

###

DELETE http://localhost:3001/api/persons/624ea3c6ad9beedf0c2df0c8

###

PUT http://localhost:3001/api/persons/624df43d83b61c8f60e980de
Content-Type: application/json

{
  "name": "Sorin",
  "number": "Vaae"
}

###

POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alessandro Deltoro",
  "number": "999-0000"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "name": "Alessandro Deltoro"
}

###
POST http://localhost:3001/api/persons
Content-Type: application/json

{
  "number": "999-0000"
}
